name: Build React App Image
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Build and Push the Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build \
          --build-arg VCS_REF=$(git rev-parse HEAD) \
          --build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") \
          -t us-central1-docker.pkg.dev/${GOOGLE_PROJECT}/super-web-app/super-web-app:amd64 \
          -f frontend/Dockerfile frontend/
          docker push us-central1-docker.pkg.dev/${GOOGLE_PROJECT}/super-web-app/super-web-app:amd64